/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * This is not part of the example test suite, it's a placeholder representing application code.
 */
package serenity_demo;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
