/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * This is not part of the example test suite, it's a placeholder representing application code.
 */
package serenity_demo;

import org.junit.runner.JUnitCore;

public class TestRunner {
    public static void main(String[] args) {
        JUnitCore.runClasses(SearchTestSuite.class);
    }
}
