/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * This is not part of the example test suite, it's a placeholder representing application code.
 */
package serenity_demo;

import net.thucydides.core.reports.html.HtmlAggregateStoryReporter;
import org.junit.runner.JUnitCore;

import java.io.File;
import java.io.IOException;

public class TestRunner {
    public static void main(String[] args) throws IOException {

        // Run the test suite.
        JUnitCore.runClasses(SearchTestSuite.class);

        // Generate the aggregated test report.
        File sourceDirectory = new File("target/site/serenity/");
        HtmlAggregateStoryReporter reporter = new HtmlAggregateStoryReporter("Serenity Cucumber Demo");
        reporter.setOutputDirectory(sourceDirectory);
        reporter.generateReportsForTestResultsFrom(sourceDirectory);
    }
}
